# Generated by Django 3.0.4 on 2020-03-24 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('powerwater', models.BooleanField(default=False)),
                ('access', models.CharField(max_length=30)),
                ('camper_size', models.CharField(max_length=30)),
                ('availability', models.TextField()),
                ('cost_per_night', models.IntegerField()),
                ('image_url', models.CharField(max_length=3255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=8, max_digits=11)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('cost_total', models.IntegerField()),
                ('campsite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campsites', to='campground.Campsite')),
            ],
        ),
    ]
