# Generated by Django 3.0.4 on 2020-03-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campground', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campsite',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=8),
        ),
        migrations.AlterField(
            model_name='campsite',
            name='lng',
            field=models.DecimalField(decimal_places=6, max_digits=8),
        ),
    ]
