# Generated by Django 3.0.4 on 2020-03-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campground', '0004_auto_20200328_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='end_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_date',
            field=models.CharField(max_length=50),
        ),
    ]
