# Generated by Django 3.0.4 on 2020-04-01 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campground', '0005_auto_20200329_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date_range',
            field=models.CharField(default=[], max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='cost_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
